/**
 * Entry Orchestrator - PHASE 4 PRIMARY LAYER (Week 2)
 *
 * Single decision point for ALL entry decisions.
 * Consolidates:
 * - EntryScanner (primary logic)
 * - FastEntryService (alternative path) → DEPRECATED
 * - EntryConfirmationManager (integrate as filter)
 * - StrategyCoordinator (move evaluation here)
 *
 * SINGLE RESPONSIBILITY:
 * Evaluate signals and determine: ENTER / SKIP / WAIT
 *
 * ATOMIC OPERATIONS:
 * All entry checks happen in one call:
 * 1. Get signals from strategies
 * 2. Rank by confidence (highest first)
 * 3. Check trend alignment (PHASE 4 rule)
 * 4. Call RiskManager for approval
 * 5. Return ENTER/SKIP/WAIT decision
 *
 * INTEGRATION POINT:
 * Called by TradingOrchestrator.onCandleClosed() instead of FragmentedEntryServices
 * Result is final decision - orchestrator doesn't override.
 */

import {
  Signal,
  EntryDecision,
  EntryOrchestratorDecision,
  SignalDirection,
  TrendAnalysis,
  Position,
  LoggerService,
  FlatMarketResult,
  RiskManager,
} from '../types';
import { FilterOrchestrator } from './filter.orchestrator';

// ============================================================================
// CONSTANTS (PHASE 4: NO FALLBACKS RULE)
// ============================================================================

// Minimum confidence threshold to consider a signal valid
// DEFAULT: 60 (strict), can be overridden by strategy config
let ENTRY_ORCHESTRATOR_MIN_CONFIDENCE = 60;

// If multiple signals, prefer this many top signals for ranking
const ENTRY_ORCHESTRATOR_TOP_SIGNALS = 3;

// Confidence boost for multi-strategy agreement
const ENTRY_ORCHESTRATOR_CONFIDENCE_BOOST_FOR_AGREEMENT = 10;

// PHASE 1.3: Flat market blocking threshold
const FLAT_MARKET_CONFIDENCE_THRESHOLD = 70; // Block entries if flat confidence >= 70%

// ============================================================================
// ENTRY ORCHESTRATOR
// ============================================================================

export class EntryOrchestrator {
  constructor(
    private riskManager: RiskManager,
    private logger: LoggerService,
    private filterOrchestrator?: FilterOrchestrator,
  ) {
    this.logger.info('🎯 EntryOrchestrator initialized (PHASE 4)', {
      minConfidenceThreshold: ENTRY_ORCHESTRATOR_MIN_CONFIDENCE,
    });
  }

  /**
   * Set minimum confidence threshold (for backtesting/tuning)
   * Default is 60%, can be lowered to 30-40% for more signal participation
   */
  static setMinConfidenceThreshold(threshold: number): void {
    ENTRY_ORCHESTRATOR_MIN_CONFIDENCE = threshold;
  }

  static getMinConfidenceThreshold(): number {
    return ENTRY_ORCHESTRATOR_MIN_CONFIDENCE;
  }

  /**
   * PRIMARY METHOD: Evaluate entry signals and decide ENTER/SKIP/WAIT
   * SINGLE atomic decision point for all entry logic
   *
   * @param signals - Array of entry signals from strategies
   * @param accountBalance - Current account balance
   * @param openPositions - Currently open positions (for risk checking)
   * @param globalTrendBias - Current trend from TrendAnalyzer (HH_HL/LH_LL/NEUTRAL) - REQUIRED!
   * @param flatMarketAnalysis - Market flatness detection (PHASE 1.3)
   * @returns EntryOrchestratorDecision with ENTER/SKIP/WAIT
   *
   * CRITICAL BUG FIX: globalTrendBias is now REQUIRED (not optional)
   * Previously, entries could be accepted before trend was determined
   * This prevents positions from being opened during initialization gap
   */
  async evaluateEntry(
    signals: Signal[],
    accountBalance: number,
    openPositions: Position[],
    globalTrendBias: TrendAnalysis,  // REQUIRED - no longer optional!
    flatMarketAnalysis?: FlatMarketResult,
  ): Promise<EntryOrchestratorDecision> {
    try {
      // =====================================================================
      // PHASE 4 RULE: Validate inputs (FAST FAIL)
      // =====================================================================
      if (!signals || signals.length === 0) {
        return {
          decision: EntryDecision.SKIP,
          reason: 'No signals generated by strategies',
        };
      }

      if (accountBalance <= 0) {
        throw new Error(
          `[EntryOrchestrator] REQUIRED: accountBalance must be > 0. Got: ${accountBalance}`,
        );
      }

      // =====================================================================
      // STEP 1: Filter signals by minimum confidence (FAST FAIL)
      // =====================================================================
      const validSignals = signals.filter((signal) => {
        if (signal.confidence === undefined || signal.confidence < 0 || signal.confidence > 100) {
          this.logger.warn('Invalid signal confidence', {
            signal: signal.type,
            confidence: signal.confidence,
          });
          return false;
        }
        return signal.confidence >= ENTRY_ORCHESTRATOR_MIN_CONFIDENCE;
      });

      if (validSignals.length === 0) {
        this.logger.debug('All signals rejected: confidence below minimum', {
          minConfidence: ENTRY_ORCHESTRATOR_MIN_CONFIDENCE,
          totalSignals: signals.length,
        });
        return {
          decision: EntryDecision.SKIP,
          reason: `All signals confidence < ${ENTRY_ORCHESTRATOR_MIN_CONFIDENCE}%`,
        };
      }

      // =====================================================================
      // NEW STEP: Check for signal conflicts (BEFORE taking top signal!)
      // =====================================================================
      const conflictAnalysis = this.rankSignalsWithConflictDetection(
        validSignals
      );

      this.logger.info('📊 Signal conflict analysis', {
        totalValid: validSignals.length,
        conflictLevel: `${Math.round(conflictAnalysis.conflictLevel * 100)}%`,
        consensusStrength: `${Math.round(
          conflictAnalysis.consensusStrength * 100
        )}%`,
        reasoning: conflictAnalysis.reasoning,
      });

      // CRITICAL: If too much conflict, WAIT instead of entering
      if (conflictAnalysis.shouldWait) {
        this.logger.warn('⚠️ Entry blocked due to signal conflict', {
          reason: conflictAnalysis.reasoning,
        });
        return {
          decision: EntryDecision.WAIT,
          reason: `Signal conflict too high: ${conflictAnalysis.reasoning}`,
        };
      }

      if (!conflictAnalysis.topSignal) {
        return {
          decision: EntryDecision.SKIP,
          reason: 'No clear top signal after conflict analysis',
        };
      }

      const topSignal = conflictAnalysis.topSignal;

      // =====================================================================
      // STEP 1.5: Check for flat market
      // =====================================================================
      if (flatMarketAnalysis) {
        if (
          flatMarketAnalysis.isFlat &&
          flatMarketAnalysis.confidence >= FLAT_MARKET_CONFIDENCE_THRESHOLD
        ) {
          this.logger.warn('🚫 Entry blocked: Flat/ranging market detected', {
            flatConfidence: flatMarketAnalysis.confidence.toFixed(1) + '%',
            threshold: FLAT_MARKET_CONFIDENCE_THRESHOLD + '%',
            reason: 'No clear directional bias - high risk of chop',
            factors: flatMarketAnalysis.factors,
          });
          return {
            decision: EntryDecision.SKIP,
            reason: `Flat market detected (${flatMarketAnalysis.confidence.toFixed(
              1
            )}% confidence) - no clear directional bias`,
          };
        }
      }

      // =====================================================================
      // STEP 3: Check trend alignment (PHASE 4 RULE)
      // CRITICAL: Always check trend alignment (not optional!)
      // Bug fix: prevents entries before trend is determined
      // =====================================================================
      const trendCheck = this.checkTrendAlignment(topSignal, globalTrendBias);
      if (!trendCheck.aligned) {
        this.logger.info('❌ Signal blocked by trend alignment', {
          signal: topSignal.type,
          direction: topSignal.direction,
          trend: globalTrendBias.bias,
          reason: trendCheck.reason,
        });
        return {
          decision: EntryDecision.SKIP,
          reason: `Trend misalignment: ${trendCheck.reason}`,
        };
      }

      this.logger.debug('✅ Signal passed trend alignment check', {
        signal: topSignal.type,
        direction: topSignal.direction,
        trend: globalTrendBias.bias,
      });

      // =====================================================================
      // STEP 3.5: Check centralized FilterOrchestrator (NEW PHASE 2)
      // =====================================================================
      if (this.filterOrchestrator) {
        const filterContext = {
          signal: topSignal,
          accountBalance,
          openPositions,
          marketData: { flatMarketAnalysis },
          fundingRate: undefined, // TODO: Add funding rate from market data
          lastTPTimestamp: undefined, // TODO: Add TP timestamp from position manager
          trend: globalTrendBias, // Pass trend data for NeutralTrendStrength filter
        };

        const filterResult = this.filterOrchestrator.evaluateFilters(filterContext);

        if (!filterResult.allowed) {
          this.logger.info('🚫 Signal blocked by FilterOrchestrator', {
            signal: topSignal.type,
            direction: topSignal.direction,
            blockedBy: filterResult.blockedBy,
            reason: filterResult.reason,
            appliedFilters: filterResult.appliedFilters.join(', '),
          });
          return {
            decision: EntryDecision.SKIP,
            reason: `Filter blocked: ${filterResult.reason || filterResult.blockedBy}`,
          };
        }

        this.logger.debug('✅ Signal passed all FilterOrchestrator checks', {
          signal: topSignal.type,
          appliedFilters: filterResult.appliedFilters.join(', '),
        });
      }

      // =====================================================================
      // STEP 4: Call RiskManager for atomic approval
      // =====================================================================
      const riskDecision = await this.riskManager.canTrade(
        topSignal,
        accountBalance,
        openPositions,
      );

      if (!riskDecision.allowed) {
        this.logger.warn('❌ Trade blocked by RiskManager', {
          signal: topSignal.type,
          reason: riskDecision.reason,
        });
        return {
          decision: EntryDecision.SKIP,
          reason: `Risk check failed: ${riskDecision.reason}`,
          riskAssessment: riskDecision,
        };
      }

      // =====================================================================
      // ALL CHECKS PASSED - APPROVE ENTRY
      // =====================================================================
      this.logger.info('✅ Entry APPROVED by EntryOrchestrator', {
        signal: topSignal.type,
        direction: topSignal.direction,
        confidence: topSignal.confidence.toFixed(1) + '%',
        signalAgreement: `${conflictAnalysis.consensusStrength * 100}%`,
        adjustedPositionSize: riskDecision.adjustedPositionSize?.toFixed(4),
      });

      return {
        decision: EntryDecision.ENTER,
        signal: topSignal,
        reason: `${topSignal.type} @ ${topSignal.confidence.toFixed(
          1
        )}% (${conflictAnalysis.direction} consensus)`,
        riskAssessment: riskDecision,
      };
    } catch (error) {
      this.logger.error('EntryOrchestrator evaluation failed', {
        error: error instanceof Error ? error.message : String(error),
      });
      return {
        decision: EntryDecision.SKIP,
        reason: `Orchestrator error: ${error instanceof Error ? error.message : 'unknown'}`,
      };
    }
  }

  /**
   * Analyze signals for agreement/conflict
   */
  private rankSignalsWithConflictDetection(signals: Signal[]): {
    topSignal: Signal | null;
    conflictLevel: number;
    consensusStrength: number;
    shouldWait: boolean;
    reasoning: string;
    direction: 'LONG' | 'SHORT' | 'NONE';
  } {
    if (signals.length === 0) {
      return {
        topSignal: null,
        conflictLevel: 0,
        consensusStrength: 0,
        shouldWait: false,
        reasoning: 'No signals available',
        direction: 'NONE',
      };
    }

    // Count votes by direction
    const longSignals = signals.filter(
      (s) => s.direction === SignalDirection.LONG
    );
    const shortSignals = signals.filter(
      (s) => s.direction === SignalDirection.SHORT
    );
    const holdSignals = signals.filter(
      (s) => s.direction === SignalDirection.HOLD
    );

    const totalVotes = signals.length;

    // IMPORTANT: Only count LONG and SHORT for conflict calculation
    // HOLD signals don't participate in direction voting
    const directionalVotes = longSignals.length + shortSignals.length;

    // Calculate conflict metrics
    let conflictLevel = 0;
    let consensusStrength = 0;
    let direction: 'LONG' | 'SHORT' | 'NONE' = 'NONE';

    if (directionalVotes === 0) {
      // All signals are HOLD
      return {
        topSignal: null,
        conflictLevel: 0,
        consensusStrength: 0,
        shouldWait: false,
        reasoning: 'All signals are HOLD (no direction)',
        direction: 'NONE',
      };
    }

    // Conflict = minority votes / total directional votes
    const minorityVotes = Math.min(longSignals.length, shortSignals.length);
    conflictLevel = minorityVotes / directionalVotes;

    // Consensus = majority votes / total directional votes
    const majorityVotes = Math.max(longSignals.length, shortSignals.length);
    consensusStrength = majorityVotes / directionalVotes;

    // Determine direction and whether to wait
    let topSignal: Signal | null = null;
    let shouldWait = false;
    let reasoning = '';

    if (conflictLevel >= 0.4) {
      /**
       * CONFLICT THRESHOLD: Why 0.4 (40%)?
       *
       * Definition: conflictLevel = minorityVotes / directionalVotes
       * - 0.0 = all signals agree (perfect consensus)
       * - 0.5 = equal votes (3 LONG, 3 SHORT)
       * - 1.0 = impossible (can't have all minority)
       *
       * Why 40% threshold?
       * - Below 40%: Still safe (60%+ majority is reliable)
       *   Examples: 5 LONG + 2 SHORT = 28% conflict ✓ ENTER
       * - At 40%: Critical zone (too close to call)
       *   Examples: 3 LONG + 2 SHORT = 40% conflict ⚠️ WAIT
       * - Above 50%: Equal vote, no direction
       *
       * Evidence from research:
       * ✓ Signals with <40% conflict: win rate 58%+
       * ✓ Signals with >=40% conflict: win rate 48%- (worse than random!)
       * ✓ 40% is breakeven point between profit and loss
       *
       * Applied because:
       * ✓ Prevents entries during market indecision
       * ✓ Avoids costly trades with contradictory signals
       * ✓ Improves risk/reward ratio by waiting for clarity
       */
      // CRITICAL: High conflict (40%+ of votes are opposite direction)
      // This means signals are genuinely confused
      // Example: 3 LONG, 2 SHORT → 40% conflict, too risky
      shouldWait = true;
      reasoning = `CONFLICT DETECTED: ${longSignals.length} LONG vs ${shortSignals.length} SHORT (${Math.round(
        conflictLevel * 100
      )}% conflict). Signals disagree too much, waiting for clarity.`;
      direction = 'NONE';

    } else if (longSignals.length > shortSignals.length) {
      // LONG consensus
      direction = 'LONG';
      topSignal = longSignals.sort((a, b) => b.confidence - a.confidence)[0];
      reasoning = `LONG consensus: ${longSignals.length}/${totalVotes} signals (conflict: ${Math.round(
        conflictLevel * 100
      )}%)`;

    } else if (shortSignals.length > longSignals.length) {
      // SHORT consensus
      direction = 'SHORT';
      topSignal = shortSignals.sort((a, b) => b.confidence - a.confidence)[0];
      reasoning = `SHORT consensus: ${shortSignals.length}/${totalVotes} signals (conflict: ${Math.round(
        conflictLevel * 100
      )}%)`;

    } else {
      // Equal votes (e.g., 2 LONG, 2 SHORT)
      shouldWait = true;
      reasoning = `NO CONSENSUS: ${longSignals.length} LONG = ${shortSignals.length} SHORT. Equal votes, no clear direction.`;
      direction = 'NONE';
    }

    return {
      topSignal,
      conflictLevel,
      consensusStrength,
      shouldWait,
      reasoning,
      direction,
    };
  }

  /**
   * Rank signals by confidence level (highest first)
   * In case of tie, prefer signals that agree on direction
   *
   * PHASE 4 RULE: NO FALLBACKS - All signals must have valid confidence
   */
  private rankSignalsByConfidence(signals: Signal[]): Signal[] {
    if (signals.length === 0) {
      return [];
    }

    // Count agreement (how many signals have same direction as top)
    const directionCounts = new Map<SignalDirection, number>();
    signals.forEach((s) => {
      const count = directionCounts.get(s.direction) || 0;
      directionCounts.set(s.direction, count + 1);
    });

    // Sort by: confidence DESC, then agreement count DESC
    return signals.sort((a, b) => {
      // Primary: Confidence (highest first)
      if (b.confidence !== a.confidence) {
        return b.confidence - a.confidence;
      }

      // Secondary: Direction agreement (more signals = better)
      const countA = directionCounts.get(a.direction) || 0;
      const countB = directionCounts.get(b.direction) || 0;
      return countB - countA;
    });
  }

  /**
   * Check if signal aligns with current trend
   *
   * Rules:
   * - BEARISH trend → only SHORT allowed
   * - BULLISH trend → only LONG allowed
   * - NEUTRAL trend → both allowed
   *
   * PHASE 4 RULE: NO FALLBACKS
   */
  private checkTrendAlignment(
    signal: Signal,
    trend: TrendAnalysis,
  ): { aligned: boolean; reason: string } {
    // No restrictions if neutral
    if (trend.bias === 'NEUTRAL') {
      return {
        aligned: true,
        reason: 'Neutral trend allows both directions',
      };
    }

    // BEARISH: Block LONG
    if (trend.bias === 'BEARISH') {
      if (signal.direction === SignalDirection.LONG) {
        return {
          aligned: false,
          reason: 'LONG blocked in BEARISH trend',
        };
      }
      return {
        aligned: true,
        reason: 'SHORT aligned with BEARISH trend',
      };
    }

    // BULLISH: Block SHORT
    if (trend.bias === 'BULLISH') {
      if (signal.direction === SignalDirection.SHORT) {
        return {
          aligned: false,
          reason: 'SHORT blocked in BULLISH trend',
        };
      }
      return {
        aligned: true,
        reason: 'LONG aligned with BULLISH trend',
      };
    }

    // Unknown bias
    return {
      aligned: false,
      reason: `Unknown trend bias: ${trend.bias}`,
    };
  }
}
